;;;; 完備化コーパス期待値ファイル生成スクリプト（フェーズ1）
;;;;
;;;; tests/resources/eq_systems/*.trs の各ファイルに対し、記号順序の並列探索を含む
;;;; 完備化 (start-completion) を実行し、成功した記号順序と生成された書き換え規則
;;;; 集合を tests/resources/eq_systems_expected/<base>.lisp へ書き出す。
;;;; 書き出した期待値は tests/src/completion-corpus-rules.lisp が「記号順序を固定
;;;; した kb-completion の再実行結果」と照合する。
;;;;
;;;; 使い方（リポジトリルートで）:
;;;;   ros run --load tests/tools/generate-completion-expected.lisp \
;;;;           --eval '(clover.tests.tools.generate-completion-expected:generate-all)' \
;;;;           --eval '(uiop:quit 0)'
;;;;
;;;; 注意:
;;;;  - 勝つ記号順序は並列探索のため実行ごとに変わりうる。期待値の再生成は
;;;;    「ベースラインの張り替え」であり、差分をレビューした上でコミットすること。
;;;;  - 規則は canonical-rewrite-rule-key（変数リネーム不変）でソートして書き出す
;;;;    ため、記号順序が同じでα同値な規則集合であればファイル内容は安定する。
;;;;  - 変数は規則ごとに初出順で (:var N) に番号付けし、gensym 名は保存しない。
;;;;  - 記号（関数・定数）は symbol-name の文字列で保存する。読み戻し側は
;;;;    パース済み equation-set の実シンボルと名前照合で対応付ける
;;;;    （LPO は ordering 内の記号を eq で引くため。termorder.lisp 参照）。

(ql:quickload :clover :silent t)

(defpackage clover.tests.tools.generate-completion-expected
  (:use :cl
        :clover.types)
  (:import-from :clover.parser
                :parse-mkbtt-expression)
  (:import-from :clover.clover
                :start-completion)
  (:import-from :clover.parameters
                :*completion-giveup-threshold*
                :*term-order-algorithm*)
  (:import-from :clover.canonicalization
                :canonical-rewrite-rule-key)
  (:import-from :clover.rename
                :rename-for-human-readable-printing)
  (:export :generate-all))
(in-package :clover.tests.tools.generate-completion-expected)


(defun %serialize-term (term var-index counter-cell)
  ;; 期待値ファイル用の項の S 式表現:
  ;;   変数   -> (:var N)   N は規則内の初出順
  ;;   定数   -> "NAME"
  ;;   関数項 -> ("NAME" arg ...)
  ;; constant は fterm のサブタイプのため fterm より先に分岐する。
  (typecase term
    (vterm
     (let* ((var (vterm.var term))
            (idx (or (gethash var var-index)
                     (setf (gethash var var-index)
                           (prog1 (car counter-cell)
                             (incf (car counter-cell)))))))
       (list :var idx)))
    (constant
     (symbol-name (constant.value term)))
    (fterm
     (cons (symbol-name (fterm.fsymbol term))
           (mapcar
             (lambda (arg) (%serialize-term arg var-index counter-cell))
             (fterm.args term))))
    (t (error "unexpected term ~A" term))))


(defun %serialize-rule (rule)
  ;; 規則を (src-sexp dst-sexp) の 2 要素リストに直列化する。
  ;; 変数番号は src/dst で共有する（規則単位で閉じた番号付け）。
  (let ((var-index (make-hash-table :test #'eq))
        (counter-cell (list 0)))
    (list (%serialize-term (rewrite-rule.src rule) var-index counter-cell)
          (%serialize-term (rewrite-rule.dst rule) var-index counter-cell))))


(defun %generate-one (trs-path out-dir)
  (let* ((filename (file-namestring trs-path))
         (base (subseq filename 0 (- (length filename) 4)))
         (equation-set (parse-mkbtt-expression
                         (uiop:read-file-string trs-path))))
    (multiple-value-bind (flag ordering rrs)
        (start-completion equation-set *completion-giveup-threshold*)
      (cond
        ((not flag)
         (warn "~A: 完備化に失敗したため期待値ファイルを生成しません" filename)
         nil)
        (t
         (let* ((rules (sort (copy-seq (rewrite-rule-set.rewrite-rules rrs))
                             #'string<
                             :key #'canonical-rewrite-rule-key))
                (readable (rename-for-human-readable-printing
                            (rewrite-rule-set rules)))
                (out-path (merge-pathnames (format nil "~A.lisp" base) out-dir)))
           (with-open-file (s out-path
                              :direction :output
                              :if-exists :supersede
                              :if-does-not-exist :create)
             (format s ";;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp~%")
             (format s ";;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。~%")
             (format s ";;;; source: ~A~%" filename)
             (format s ";;;;~%")
             (format s ";;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）~%")
             (dolist (r (rewrite-rule-set.rewrite-rules readable))
               (format s ";;;;   ~A~%" r))
             (let ((*print-pretty* nil)
                   (*print-readably* nil))
               (format s "(:term-order-algorithm ~S~%" *term-order-algorithm*)
               (format s " :giveup-threshold ~S~%" *completion-giveup-threshold*)
               (format s " :ordering ~S~%"
                       (mapcar #'symbol-name
                               (function-symbol-ordering.ordering ordering)))
               (format s " :rules~%")
               (write-string " (" s)
               (loop :for rule :in rules
                     :for firstp := t :then nil
                     :do (unless firstp
                           (format s "~%  "))
                         (format s "~S" (%serialize-rule rule)))
               (format s "))~%")))
           t))))))


(defun generate-all ()
  (let* ((src-dir (asdf:system-relative-pathname
                    :clover "tests/resources/eq_systems/"))
         (out-dir (asdf:system-relative-pathname
                    :clover "tests/resources/eq_systems_expected/"))
         (files (sort (uiop:directory-files src-dir "*.trs")
                      #'string< :key #'namestring))
         (success 0)
         (failure 0))
    (ensure-directories-exist out-dir)
    (dolist (trs-path files)
      (format t "~&generating: ~A ... " (file-namestring trs-path))
      (force-output)
      (cond
        ((%generate-one trs-path out-dir)
         (incf success)
         (format t "ok~%"))
        (t
         (incf failure)
         (format t "FAILED~%"))))
    (format t "~&done: ~A generated, ~A failed~%" success failure)
    (zerop failure)))
