;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: ASK93_6.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   a(x) -> i(y(x))
;;;;   d(g(c(x))) -> e(g(c(x)))
;;;;   i(g(c(x))) -> e(f(c(x)))
;;;;   j(f(x)) -> x
;;;;   o(x) -> x(h(c(x)))
;;;;   u(b(c(x))) -> x(h(c(x)))
;;;;   w(e(x)) -> h(j(x))
;;;;   x(h(j(g(x)))) -> x(h(x))
;;;;   x(w(d(g(x)))) -> u(b(x))
;;;;   x(w(d(y(x)))) -> u(x)
;;;;   x(w(i(x))) -> x(w(d(x)))
;;;;   y(b(x)) -> g(x)
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("U" "C" "F" "X" "H" "J" "O" "W" "E" "D" "B" "G" "I" "Y" "A")
 :rules
 ((("A" (:VAR 0)) ("I" ("Y" (:VAR 0))))
  (("D" ("G" ("C" (:VAR 0)))) ("E" ("G" ("C" (:VAR 0)))))
  (("I" ("G" ("C" (:VAR 0)))) ("E" ("F" ("C" (:VAR 0)))))
  (("J" ("F" (:VAR 0))) (:VAR 0))
  (("O" (:VAR 0)) ("X" ("H" ("C" (:VAR 0)))))
  (("U" ("B" ("C" (:VAR 0)))) ("X" ("H" ("C" (:VAR 0)))))
  (("W" ("E" (:VAR 0))) ("H" ("J" (:VAR 0))))
  (("X" ("H" ("J" ("G" (:VAR 0))))) ("X" ("H" (:VAR 0))))
  (("X" ("W" ("D" ("G" (:VAR 0))))) ("U" ("B" (:VAR 0))))
  (("X" ("W" ("D" ("Y" (:VAR 0))))) ("U" (:VAR 0)))
  (("X" ("W" ("I" (:VAR 0)))) ("X" ("W" ("D" (:VAR 0)))))
  (("Y" ("B" (:VAR 0))) ("G" (:VAR 0)))))
