;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: ASK93_1.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   a(b(x)) -> w(a(x))
;;;;   w(a(c(x))) -> a(c(x))
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("W" "B" "C" "A")
 :rules
 ((("A" ("B" (:VAR 0))) ("W" ("A" (:VAR 0))))
  (("W" ("A" ("C" (:VAR 0)))) ("A" ("C" (:VAR 0))))))
