;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: aufgabe3_2.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   g(x) -> f(f(x))
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("F" "G")
 :rules
 ((("G" (:VAR 0)) ("F" ("F" (:VAR 0))))))
