;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: BD94_peano.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   *(x,0) -> 0
;;;;   *(y,s(x)) -> +(*(y,x),y)
;;;;   +(x,0) -> x
;;;;   +(x,s(y)) -> s(+(x,y))
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("0" "S" "+" "*")
 :rules
 ((("*" (:VAR 0) "0") "0")
  (("*" (:VAR 0) ("S" (:VAR 1))) ("+" ("*" (:VAR 0) (:VAR 1)) (:VAR 0)))
  (("+" (:VAR 0) "0") (:VAR 0))
  (("+" (:VAR 0) ("S" (:VAR 1))) ("S" ("+" (:VAR 0) (:VAR 1))))))
