;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: BD94_collapse.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   B -> A
;;;;   C -> A
;;;;   f(A,x) -> A
;;;;   f(x,A) -> x
;;;;   g(x) -> x
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("A" "B" "C" "F" "G")
 :rules
 (("B" "A")
  ("C" "A")
  (("F" "A" (:VAR 0)) "A")
  (("F" (:VAR 0) "A") (:VAR 0))
  (("G" (:VAR 0)) (:VAR 0))))
