;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: BD94_sqrt.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   +(0,0) -> 0
;;;;   i(0) -> 0
;;;;   sqrt(0) -> 0
;;;;   sqrt(+(i(x),x)) -> 0
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("0" "I" "+" "SQRT")
 :rules
 ((("+" "0" "0") "0")
  (("I" "0") "0")
  (("SQRT" "0") "0")
  (("SQRT" ("+" ("I" (:VAR 0)) (:VAR 0))) "0")))
