;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: BH96_fac8_theory.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   *(x,0) -> 0
;;;;   *(x,s(Y)) -> +(*(x,Y),x)
;;;;   +(x,0) -> x
;;;;   +(x,s(Y)) -> s(+(x,Y))
;;;;   fac(0) -> s(0)
;;;;   fac(s(x)) -> *(s(x),fac(x))
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("0" "Y" "S" "+" "*" "FAC")
 :rules
 ((("*" (:VAR 0) "0") "0")
  (("*" (:VAR 0) ("S" "Y")) ("+" ("*" (:VAR 0) "Y") (:VAR 0)))
  (("+" (:VAR 0) "0") (:VAR 0))
  (("+" (:VAR 0) ("S" "Y")) ("S" ("+" (:VAR 0) "Y")))
  (("FAC" "0") ("S" "0"))
  (("FAC" ("S" (:VAR 0))) ("*" ("S" (:VAR 0)) ("FAC" (:VAR 0))))))
