;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: Les83_fib.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   +(0,x) -> x
;;;;   +(+(x,y),z) -> +(x,+(y,z))
;;;;   +(s(x),y) -> s(+(x,y))
;;;;   dfib(0,x) -> x
;;;;   dfib(s(0),x) -> s(x)
;;;;   dfib(s(s(x)),y) -> dfib(s(x),dfib(x,y))
;;;;   fib(0) -> 0
;;;;   fib(s(0)) -> s(0)
;;;;   fib(s(s(x))) -> +(fib(x),fib(s(x)))
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("0" "S" "+" "FIB" "DFIB")
 :rules
 ((("+" "0" (:VAR 0)) (:VAR 0))
  (("+" ("+" (:VAR 0) (:VAR 1)) (:VAR 2)) ("+" (:VAR 0) ("+" (:VAR 1) (:VAR 2))))
  (("+" ("S" (:VAR 0)) (:VAR 1)) ("S" ("+" (:VAR 0) (:VAR 1))))
  (("DFIB" "0" (:VAR 0)) (:VAR 0))
  (("DFIB" ("S" "0") (:VAR 0)) ("S" (:VAR 0)))
  (("DFIB" ("S" ("S" (:VAR 0))) (:VAR 1)) ("DFIB" ("S" (:VAR 0)) ("DFIB" (:VAR 0) (:VAR 1))))
  (("FIB" "0") "0")
  (("FIB" ("S" "0")) ("S" "0"))
  (("FIB" ("S" ("S" (:VAR 0)))) ("+" ("FIB" (:VAR 0)) ("FIB" ("S" (:VAR 0)))))))
