;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: Les83_subset.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   eq(0,0) -> TT
;;;;   eq(0,s(x)) -> FF
;;;;   eq(s(x),0) -> FF
;;;;   eq(s(x),s(y)) -> eq(x,y)
;;;;   has(EMPTY,x) -> FF
;;;;   has(+(y,x),z) -> if(eq(x,z),TT,has(y,z))
;;;;   if(FF,x,y) -> y
;;;;   if(TT,y,x) -> y
;;;;   if(x,TT,FF) -> x
;;;;   if(x,y,y) -> y
;;;;   subset(EMPTY,x) -> TT
;;;;   subset(+(y,x),z) -> if(has(z,x),subset(y,z),FF)
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("0" "EMPTY" "FF" "TT" "IF" "EQ" "HAS" "SUBSET" "+" "S")
 :rules
 ((("EQ" "0" "0") "TT")
  (("EQ" "0" ("S" (:VAR 0))) "FF")
  (("EQ" ("S" (:VAR 0)) "0") "FF")
  (("EQ" ("S" (:VAR 0)) ("S" (:VAR 1))) ("EQ" (:VAR 0) (:VAR 1)))
  (("HAS" "EMPTY" (:VAR 0)) "FF")
  (("HAS" ("+" (:VAR 0) (:VAR 1)) (:VAR 2)) ("IF" ("EQ" (:VAR 1) (:VAR 2)) "TT" ("HAS" (:VAR 0) (:VAR 2))))
  (("IF" "FF" (:VAR 0) (:VAR 1)) (:VAR 1))
  (("IF" "TT" (:VAR 0) (:VAR 1)) (:VAR 0))
  (("IF" (:VAR 0) "TT" "FF") (:VAR 0))
  (("IF" (:VAR 0) (:VAR 1) (:VAR 1)) (:VAR 1))
  (("SUBSET" "EMPTY" (:VAR 0)) "TT")
  (("SUBSET" ("+" (:VAR 0) (:VAR 1)) (:VAR 2)) ("IF" ("HAS" (:VAR 2) (:VAR 1)) ("SUBSET" (:VAR 0) (:VAR 2)) "FF"))))
