;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: OKW95_dt1_theory.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   +(x,0) -> x
;;;;   +(x,s(y)) -> s(+(x,y))
;;;;   -(x,0) -> x
;;;;   -(s(x),s(y)) -> -(x,y)
;;;;   dfib(0) -> s(0)
;;;;   dfib(s(0)) -> s(0)
;;;;   dfib(s(s(x))) -> +(dfib(s(x)),+(dfib(x),dfib(x)))
;;;;   fib(0) -> s(0)
;;;;   fib(s(0)) -> s(0)
;;;;   fib(s(s(x))) -> +(fib(s(x)),fib(x))
;;;;   p(x) -> -(x,s(0))
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("0" "S" "-" "P" "+" "DFIB" "FIB")
 :rules
 ((("+" (:VAR 0) "0") (:VAR 0))
  (("+" (:VAR 0) ("S" (:VAR 1))) ("S" ("+" (:VAR 0) (:VAR 1))))
  (("-" (:VAR 0) "0") (:VAR 0))
  (("-" ("S" (:VAR 0)) ("S" (:VAR 1))) ("-" (:VAR 0) (:VAR 1)))
  (("DFIB" "0") ("S" "0"))
  (("DFIB" ("S" "0")) ("S" "0"))
  (("DFIB" ("S" ("S" (:VAR 0)))) ("+" ("DFIB" ("S" (:VAR 0))) ("+" ("DFIB" (:VAR 0)) ("DFIB" (:VAR 0)))))
  (("FIB" "0") ("S" "0"))
  (("FIB" ("S" "0")) ("S" "0"))
  (("FIB" ("S" ("S" (:VAR 0)))) ("+" ("FIB" ("S" (:VAR 0))) ("FIB" (:VAR 0))))
  (("P" (:VAR 0)) ("-" (:VAR 0) ("S" "0")))))
