;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: Sim91_sims2.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   r(x) -> x
;;;;   s(x) -> x
;;;;   t(x) -> x
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("T" "S" "R")
 :rules
 ((("R" (:VAR 0)) (:VAR 0))
  (("S" (:VAR 0)) (:VAR 0))
  (("T" (:VAR 0)) (:VAR 0))))
