;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: SK90_3.30.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   f(g(x),y) -> A
;;;;   h(x) -> A
;;;;   k(A,A) -> A
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("A" "H" "F" "G" "K")
 :rules
 ((("F" ("G" (:VAR 0)) (:VAR 1)) "A")
  (("H" (:VAR 0)) "A")
  (("K" "A" "A") "A")))
