;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: SK90_3.20.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   .(NIL,x) -> x
;;;;   .(end(x,y),z) -> .(x,f(y,z))
;;;;   and(TRUE,TRUE) -> TRUE
;;;;   eq(NIL,end(x,y)) -> FALSE
;;;;   eq(x,x) -> TRUE
;;;;   eq(end(x,y),NIL) -> FALSE
;;;;   eq(end(z,x),end(w,y)) -> and(eq(x,y),eq(z,w))
;;;;   f(x,NIL) -> end(NIL,x)
;;;;   f(x,end(y,z)) -> end(f(x,y),z)
;;;;   null(NIL) -> TRUE
;;;;   null(end(x,y)) -> FALSE
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("FALSE" "NIL" "TRUE" "END" "NULL" "F" "." "AND" "EQ")
 :rules
 ((("." "NIL" (:VAR 0)) (:VAR 0))
  (("." ("END" (:VAR 0) (:VAR 1)) (:VAR 2)) ("." (:VAR 0) ("F" (:VAR 1) (:VAR 2))))
  (("AND" "TRUE" "TRUE") "TRUE")
  (("EQ" "NIL" ("END" (:VAR 0) (:VAR 1))) "FALSE")
  (("EQ" (:VAR 0) (:VAR 0)) "TRUE")
  (("EQ" ("END" (:VAR 0) (:VAR 1)) "NIL") "FALSE")
  (("EQ" ("END" (:VAR 0) (:VAR 1)) ("END" (:VAR 2) (:VAR 3))) ("AND" ("EQ" (:VAR 1) (:VAR 3)) ("EQ" (:VAR 0) (:VAR 2))))
  (("F" (:VAR 0) "NIL") ("END" "NIL" (:VAR 0)))
  (("F" (:VAR 0) ("END" (:VAR 1) (:VAR 2))) ("END" ("F" (:VAR 0) (:VAR 1)) (:VAR 2)))
  (("NULL" "NIL") "TRUE")
  (("NULL" ("END" (:VAR 0) (:VAR 1))) "FALSE")))
