;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: SK90_3.28.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   a(b(a(x))) -> b(x)
;;;;   a(b(b(x))) -> b(b(a(x)))
;;;;   a(b(c(x))) -> w(w(b(b(c(a(b(x)))))))
;;;;   a(c(x)) -> w(a(x))
;;;;   a(w(x)) -> c(a(x))
;;;;   b(c(b(x))) -> c(x)
;;;;   b(c(c(x))) -> c(c(b(x)))
;;;;   b(w(x)) -> w(w(b(c(x))))
;;;;   c(w(x)) -> x
;;;;   u(x) -> w(b(c(a(b(x)))))
;;;;   v(x) -> w(b(c(x)))
;;;;   w(c(x)) -> x
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("C" "W" "B" "V" "A" "U")
 :rules
 ((("A" ("B" ("A" (:VAR 0)))) ("B" (:VAR 0)))
  (("A" ("B" ("B" (:VAR 0)))) ("B" ("B" ("A" (:VAR 0)))))
  (("A" ("B" ("C" (:VAR 0)))) ("W" ("W" ("B" ("B" ("C" ("A" ("B" (:VAR 0)))))))))
  (("A" ("C" (:VAR 0))) ("W" ("A" (:VAR 0))))
  (("A" ("W" (:VAR 0))) ("C" ("A" (:VAR 0))))
  (("B" ("C" ("B" (:VAR 0)))) ("C" (:VAR 0)))
  (("B" ("C" ("C" (:VAR 0)))) ("C" ("C" ("B" (:VAR 0)))))
  (("B" ("W" (:VAR 0))) ("W" ("W" ("B" ("C" (:VAR 0))))))
  (("C" ("W" (:VAR 0))) (:VAR 0))
  (("U" (:VAR 0)) ("W" ("B" ("C" ("A" ("B" (:VAR 0)))))))
  (("V" (:VAR 0)) ("W" ("B" ("C" (:VAR 0)))))
  (("W" ("C" (:VAR 0))) (:VAR 0))))
