;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: SK90_3.16.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   .(car(x),cdr(x)) -> x
;;;;   atom(x) -> FALSE
;;;;   car(.(y,x)) -> y
;;;;   cdr(.(x,y)) -> y
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("FALSE" "CDR" "." "ATOM" "CAR")
 :rules
 ((("." ("CAR" (:VAR 0)) ("CDR" (:VAR 0))) (:VAR 0))
  (("ATOM" (:VAR 0)) "FALSE")
  (("CAR" ("." (:VAR 0) (:VAR 1))) (:VAR 0))
  (("CDR" ("." (:VAR 0) (:VAR 1))) (:VAR 1))))
