;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: SK90_3.23.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   b(a(x)) -> a(c(x))
;;;;   b(d(x)) -> x
;;;;   b(e(x)) -> a(x)
;;;;   c(a(x)) -> a(c(x))
;;;;   c(e(x)) -> a(x)
;;;;   d(a(x)) -> e(x)
;;;;   e(a(x)) -> a(e(x))
;;;;   e(c(x)) -> a(x)
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("A" "E" "C" "D" "B")
 :rules
 ((("B" ("A" (:VAR 0))) ("A" ("C" (:VAR 0))))
  (("B" ("D" (:VAR 0))) (:VAR 0))
  (("B" ("E" (:VAR 0))) ("A" (:VAR 0)))
  (("C" ("A" (:VAR 0))) ("A" ("C" (:VAR 0))))
  (("C" ("E" (:VAR 0))) ("A" (:VAR 0)))
  (("D" ("A" (:VAR 0))) ("E" (:VAR 0)))
  (("E" ("A" (:VAR 0))) ("A" ("E" (:VAR 0))))
  (("E" ("C" (:VAR 0))) ("A" (:VAR 0)))))
