;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: SK90_3.10.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   *(ONE,x) -> x
;;;;   *(x,ONE) -> x
;;;;   f(ONE,x) -> x
;;;;   f(x,*(x,y)) -> y
;;;;   f(x,x) -> ONE
;;;;   g(*(y,x),x) -> y
;;;;   g(x,ONE) -> x
;;;;   g(x,x) -> ONE
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("ONE" "G" "*" "F")
 :rules
 ((("*" "ONE" (:VAR 0)) (:VAR 0))
  (("*" (:VAR 0) "ONE") (:VAR 0))
  (("F" "ONE" (:VAR 0)) (:VAR 0))
  (("F" (:VAR 0) ("*" (:VAR 0) (:VAR 1))) (:VAR 1))
  (("F" (:VAR 0) (:VAR 0)) "ONE")
  (("G" ("*" (:VAR 0) (:VAR 1)) (:VAR 1)) (:VAR 0))
  (("G" (:VAR 0) "ONE") (:VAR 0))
  (("G" (:VAR 0) (:VAR 0)) "ONE")))
