;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: SK90_3.02.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   +(+(x,y),z) -> +(x,+(y,z))
;;;;   f(+(x,y)) -> +(f(x),f(y))
;;;;   f(f(x)) -> x
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("+" "F")
 :rules
 ((("+" ("+" (:VAR 0) (:VAR 1)) (:VAR 2)) ("+" (:VAR 0) ("+" (:VAR 1) (:VAR 2))))
  (("F" ("+" (:VAR 0) (:VAR 1))) ("+" ("F" (:VAR 0)) ("F" (:VAR 1))))
  (("F" ("F" (:VAR 0))) (:VAR 0))))
