;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: SK90_3.24.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   a(x) -> b(x)
;;;;   b(b(b(x))) -> b(b(x))
;;;;   c(x) -> b(x)
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("B" "C" "A")
 :rules
 ((("A" (:VAR 0)) ("B" (:VAR 0)))
  (("B" ("B" ("B" (:VAR 0)))) ("B" ("B" (:VAR 0))))
  (("C" (:VAR 0)) ("B" (:VAR 0)))))
