;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: SK90_3.13.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   *(*(x,y),z) -> *(x,*(y,z))
;;;;   *(x,1) -> x
;;;;   *(x,*(1,y)) -> *(x,y)
;;;;   +(+(x,y),z) -> +(x,+(y,z))
;;;;   +(x,0) -> x
;;;;   +(x,+(0,y)) -> +(x,y)
;;;;   exp(0) -> 1
;;;;   exp(+(x,y)) -> *(exp(x),exp(y))
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("0" "1" "*" "+" "EXP")
 :rules
 ((("*" ("*" (:VAR 0) (:VAR 1)) (:VAR 2)) ("*" (:VAR 0) ("*" (:VAR 1) (:VAR 2))))
  (("*" (:VAR 0) "1") (:VAR 0))
  (("*" (:VAR 0) ("*" "1" (:VAR 1))) ("*" (:VAR 0) (:VAR 1)))
  (("+" ("+" (:VAR 0) (:VAR 1)) (:VAR 2)) ("+" (:VAR 0) ("+" (:VAR 1) (:VAR 2))))
  (("+" (:VAR 0) "0") (:VAR 0))
  (("+" (:VAR 0) ("+" "0" (:VAR 1))) ("+" (:VAR 0) (:VAR 1)))
  (("EXP" "0") "1")
  (("EXP" ("+" (:VAR 0) (:VAR 1))) ("*" ("EXP" (:VAR 0)) ("EXP" (:VAR 1))))))
