;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: SK90_3.32.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   f(y,x) -> y
;;;;   g(g(x)) -> x
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("G" "F")
 :rules
 ((("F" (:VAR 0) (:VAR 1)) (:VAR 0))
  (("G" ("G" (:VAR 0))) (:VAR 0))))
