;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: SK90_3.21.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   cdr(NIL) -> NIL
;;;;   cons(x,NIL) -> x
;;;;   f(x,NIL) -> NIL
;;;;   g(y,x) -> y
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("NIL" "CONS" "CDR" "F" "G")
 :rules
 ((("CDR" "NIL") "NIL")
  (("CONS" (:VAR 0) "NIL") (:VAR 0))
  (("F" (:VAR 0) "NIL") "NIL")
  (("G" (:VAR 0) (:VAR 1)) (:VAR 0))))
