;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: SK90_3.31.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   f(y,h(x)) -> j(y)
;;;;   f(h(y),x) -> j(h(y))
;;;;   i(x) -> g(f(x,x))
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("G" "J" "F" "I" "H")
 :rules
 ((("F" (:VAR 0) ("H" (:VAR 1))) ("J" (:VAR 0)))
  (("F" ("H" (:VAR 0)) (:VAR 1)) ("J" ("H" (:VAR 0))))
  (("I" (:VAR 0)) ("G" ("F" (:VAR 0) (:VAR 0))))))
