;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: SK90_3.33.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   f(x) -> x
;;;;   g(A) -> A
;;;;   g(g(x)) -> x
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("A" "F" "G")
 :rules
 ((("F" (:VAR 0)) (:VAR 0))
  (("G" "A") "A")
  (("G" ("G" (:VAR 0))) (:VAR 0))))
