;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: SK90_3.17.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   &(x,x) -> x
;;;;   or(&(x,z),&(y,z)) -> &(or(x,y),z)
;;;;   or(&(x,y),y) -> &(or(x,y),y)
;;;;   or(y,&(x,y)) -> &(or(y,x),y)
;;;;   or(x,x) -> x
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("&" "OR")
 :rules
 ((("&" (:VAR 0) (:VAR 0)) (:VAR 0))
  (("OR" ("&" (:VAR 0) (:VAR 1)) ("&" (:VAR 2) (:VAR 1))) ("&" ("OR" (:VAR 0) (:VAR 2)) (:VAR 1)))
  (("OR" ("&" (:VAR 0) (:VAR 1)) (:VAR 1)) ("&" ("OR" (:VAR 0) (:VAR 1)) (:VAR 1)))
  (("OR" (:VAR 0) ("&" (:VAR 1) (:VAR 0))) ("&" ("OR" (:VAR 0) (:VAR 1)) (:VAR 0)))
  (("OR" (:VAR 0) (:VAR 0)) (:VAR 0))))
