;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: SK90_3.14.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   f(0,x) -> x
;;;;   f(f(x,0),0) -> x
;;;;   f(s(x),y) -> s(f(x,y))
;;;;   g(0,x) -> x
;;;;   g(s(x),y) -> f(g(x,y),0)
;;;;   h(0) -> s(0)
;;;;   s(s(x)) -> x
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("0" "S" "H" "F" "G")
 :rules
 ((("F" "0" (:VAR 0)) (:VAR 0))
  (("F" ("F" (:VAR 0) "0") "0") (:VAR 0))
  (("F" ("S" (:VAR 0)) (:VAR 1)) ("S" ("F" (:VAR 0) (:VAR 1))))
  (("G" "0" (:VAR 0)) (:VAR 0))
  (("G" ("S" (:VAR 0)) (:VAR 1)) ("F" ("G" (:VAR 0) (:VAR 1)) "0"))
  (("H" "0") ("S" "0"))
  (("S" ("S" (:VAR 0))) (:VAR 0))))
