;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: SK90_3.25.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   a(a(a(b(x)))) -> a(b(a(a(x))))
;;;;   a(b(a(a(b(x))))) -> a(x)
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("B" "A")
 :rules
 ((("A" ("A" ("A" ("B" (:VAR 0))))) ("A" ("B" ("A" ("A" (:VAR 0))))))
  (("A" ("B" ("A" ("A" ("B" (:VAR 0)))))) ("A" (:VAR 0)))))
