;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: SK90_3.11.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   +(x,0) -> x
;;;;   p(x) -> x
;;;;   s(x) -> x
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("0" "+" "S" "P")
 :rules
 ((("+" (:VAR 0) "0") (:VAR 0))
  (("P" (:VAR 0)) (:VAR 0))
  (("S" (:VAR 0)) (:VAR 0))))
