;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: SK90_3.29.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   a(c(x)) -> e(a(x))
;;;;   a(d(x)) -> v(a(x))
;;;;   b(c(x)) -> e(b(x))
;;;;   b(d(x)) -> v(b(x))
;;;;   d(w(x)) -> c(w(x))
;;;;   e(a(w(x))) -> v(a(w(x)))
;;;;   e(b(w(x))) -> v(a(w(x)))
;;;;   u(x) -> c(w(x))
;;;;   v(b(w(x))) -> v(a(w(x)))
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("V" "E" "C" "A" "D" "B" "W" "U")
 :rules
 ((("A" ("C" (:VAR 0))) ("E" ("A" (:VAR 0))))
  (("A" ("D" (:VAR 0))) ("V" ("A" (:VAR 0))))
  (("B" ("C" (:VAR 0))) ("E" ("B" (:VAR 0))))
  (("B" ("D" (:VAR 0))) ("V" ("B" (:VAR 0))))
  (("D" ("W" (:VAR 0))) ("C" ("W" (:VAR 0))))
  (("E" ("A" ("W" (:VAR 0)))) ("V" ("A" ("W" (:VAR 0)))))
  (("E" ("B" ("W" (:VAR 0)))) ("V" ("A" ("W" (:VAR 0)))))
  (("U" (:VAR 0)) ("C" ("W" (:VAR 0))))
  (("V" ("B" ("W" (:VAR 0)))) ("V" ("A" ("W" (:VAR 0)))))))
