;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: SK90_3.18.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   @(NIL,x) -> x
;;;;   @(.(x,y),z) -> .(x,@(y,z))
;;;;   rev(NIL) -> NIL
;;;;   rev(.(y,x)) -> @(rev(x),.(y,NIL))
;;;;   rev(@(y,.(x,NIL))) -> .(x,rev(y))
;;;;   rev(rev(x)) -> x
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("NIL" "." "@" "REV")
 :rules
 ((("@" "NIL" (:VAR 0)) (:VAR 0))
  (("@" ("." (:VAR 0) (:VAR 1)) (:VAR 2)) ("." (:VAR 0) ("@" (:VAR 1) (:VAR 2))))
  (("REV" "NIL") "NIL")
  (("REV" ("." (:VAR 0) (:VAR 1))) ("@" ("REV" (:VAR 1)) ("." (:VAR 0) "NIL")))
  (("REV" ("@" (:VAR 0) ("." (:VAR 1) "NIL"))) ("." (:VAR 1) ("REV" (:VAR 0))))
  (("REV" ("REV" (:VAR 0))) (:VAR 0))))
