;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: slothrop_fgh.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   f(x) -> A
;;;;   g(x,y) -> A
;;;;   h(x,y) -> A
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("A" "G" "H" "F")
 :rules
 ((("F" (:VAR 0)) "A")
  (("G" (:VAR 0) (:VAR 1)) "A")
  (("H" (:VAR 0) (:VAR 1)) "A")))
