;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: slothrop_ackermann.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   a(Z,x) -> s(x)
;;;;   a(s(x),Z) -> a(x,s(Z))
;;;;   a(s(x),s(y)) -> a(x,a(s(x),y))
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("Z" "S" "A")
 :rules
 ((("A" "Z" (:VAR 0)) ("S" (:VAR 0)))
  (("A" ("S" (:VAR 0)) "Z") ("A" (:VAR 0) ("S" "Z")))
  (("A" ("S" (:VAR 0)) ("S" (:VAR 1))) ("A" (:VAR 0) ("A" ("S" (:VAR 0)) (:VAR 1))))))
