;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: slothrop_hard.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   plus(x,Z) -> x
;;;;   plus(x,s(y)) -> s(plus(x,y))
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("Z" "S" "PLUS")
 :rules
 ((("PLUS" (:VAR 0) "Z") (:VAR 0))
  (("PLUS" (:VAR 0) ("S" (:VAR 1))) ("S" ("PLUS" (:VAR 0) (:VAR 1))))))
