;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: slothrop_groups_conj.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   f(E,x) -> x
;;;;   f(x,E) -> x
;;;;   f(x,f(i(x),y)) -> y
;;;;   f(x,i(x)) -> E
;;;;   f(f(x,y),z) -> f(x,f(y,z))
;;;;   f(i(x),x) -> E
;;;;   f(i(x),f(x,y)) -> y
;;;;   i(E) -> E
;;;;   i(f(y,x)) -> f(i(x),i(y))
;;;;   i(i(x)) -> x
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("E" "F" "I")
 :rules
 ((("F" "E" (:VAR 0)) (:VAR 0))
  (("F" (:VAR 0) "E") (:VAR 0))
  (("F" (:VAR 0) ("F" ("I" (:VAR 0)) (:VAR 1))) (:VAR 1))
  (("F" (:VAR 0) ("I" (:VAR 0))) "E")
  (("F" ("F" (:VAR 0) (:VAR 1)) (:VAR 2)) ("F" (:VAR 0) ("F" (:VAR 1) (:VAR 2))))
  (("F" ("I" (:VAR 0)) (:VAR 0)) "E")
  (("F" ("I" (:VAR 0)) ("F" (:VAR 0) (:VAR 1))) (:VAR 1))
  (("I" "E") "E")
  (("I" ("F" (:VAR 0) (:VAR 1))) ("F" ("I" (:VAR 1)) ("I" (:VAR 0))))
  (("I" ("I" (:VAR 0))) (:VAR 0))))
