;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: TPDB_zantema_z115.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   a(a(a(a(x)))) -> c(c(c(x)))
;;;;   a(a(c(x))) -> c(a(a(x)))
;;;;   a(a(d(x))) -> c(c(c(x)))
;;;;   a(c(a(a(x)))) -> c(c(c(x)))
;;;;   a(c(c(x))) -> c(c(c(x)))
;;;;   b(x) -> c(c(x))
;;;;   c(c(a(a(x)))) -> c(c(c(x)))
;;;;   c(c(c(a(x)))) -> c(c(c(x)))
;;;;   c(c(c(c(x)))) -> c(c(c(x)))
;;;;   c(d(x)) -> a(a(x))
;;;;   d(a(a(x))) -> c(c(c(x)))
;;;;   d(c(x)) -> a(a(x))
;;;;   d(d(x)) -> c(c(a(c(x))))
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("C" "A" "B" "D")
 :rules
 ((("A" ("A" ("A" ("A" (:VAR 0))))) ("C" ("C" ("C" (:VAR 0)))))
  (("A" ("A" ("C" (:VAR 0)))) ("C" ("A" ("A" (:VAR 0)))))
  (("A" ("A" ("D" (:VAR 0)))) ("C" ("C" ("C" (:VAR 0)))))
  (("A" ("C" ("A" ("A" (:VAR 0))))) ("C" ("C" ("C" (:VAR 0)))))
  (("A" ("C" ("C" (:VAR 0)))) ("C" ("C" ("C" (:VAR 0)))))
  (("B" (:VAR 0)) ("C" ("C" (:VAR 0))))
  (("C" ("C" ("A" ("A" (:VAR 0))))) ("C" ("C" ("C" (:VAR 0)))))
  (("C" ("C" ("C" ("A" (:VAR 0))))) ("C" ("C" ("C" (:VAR 0)))))
  (("C" ("C" ("C" ("C" (:VAR 0))))) ("C" ("C" ("C" (:VAR 0)))))
  (("C" ("D" (:VAR 0))) ("A" ("A" (:VAR 0))))
  (("D" ("A" ("A" (:VAR 0)))) ("C" ("C" ("C" (:VAR 0)))))
  (("D" ("C" (:VAR 0))) ("A" ("A" (:VAR 0))))
  (("D" ("D" (:VAR 0))) ("C" ("C" ("A" ("C" (:VAR 0))))))))
