;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: TPDB_secret2006_torpa_secr10.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   a(a(a(a(x)))) -> a(a(a(x)))
;;;;   a(a(a(c(x)))) -> a(a(a(x)))
;;;;   a(a(b(a(x)))) -> a(a(x))
;;;;   a(b(a(a(x)))) -> c(a(a(x)))
;;;;   a(c(a(x))) -> a(a(a(x)))
;;;;   b(a(a(c(x)))) -> b(a(a(a(x))))
;;;;   b(a(b(x))) -> b(x)
;;;;   b(c(a(a(x)))) -> b(a(a(x)))
;;;;   c(a(a(a(x)))) -> a(a(a(x)))
;;;;   c(a(a(c(x)))) -> a(a(a(x)))
;;;;   c(a(c(x))) -> a(a(c(x)))
;;;;   c(b(x)) -> a(a(b(x)))
;;;;   c(c(x)) -> c(a(a(x)))
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("A" "C" "B")
 :rules
 ((("A" ("A" ("A" ("A" (:VAR 0))))) ("A" ("A" ("A" (:VAR 0)))))
  (("A" ("A" ("A" ("C" (:VAR 0))))) ("A" ("A" ("A" (:VAR 0)))))
  (("A" ("A" ("B" ("A" (:VAR 0))))) ("A" ("A" (:VAR 0))))
  (("A" ("B" ("A" ("A" (:VAR 0))))) ("C" ("A" ("A" (:VAR 0)))))
  (("A" ("C" ("A" (:VAR 0)))) ("A" ("A" ("A" (:VAR 0)))))
  (("B" ("A" ("A" ("C" (:VAR 0))))) ("B" ("A" ("A" ("A" (:VAR 0))))))
  (("B" ("A" ("B" (:VAR 0)))) ("B" (:VAR 0)))
  (("B" ("C" ("A" ("A" (:VAR 0))))) ("B" ("A" ("A" (:VAR 0)))))
  (("C" ("A" ("A" ("A" (:VAR 0))))) ("A" ("A" ("A" (:VAR 0)))))
  (("C" ("A" ("A" ("C" (:VAR 0))))) ("A" ("A" ("A" (:VAR 0)))))
  (("C" ("A" ("C" (:VAR 0)))) ("A" ("A" ("C" (:VAR 0)))))
  (("C" ("B" (:VAR 0))) ("A" ("A" ("B" (:VAR 0)))))
  (("C" ("C" (:VAR 0))) ("C" ("A" ("A" (:VAR 0)))))))
