;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: TPDB_secret2006_torpa_secr4.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   a(a(x)) -> a(x)
;;;;   a(c(x)) -> a(x)
;;;;   a(d(x)) -> a(x)
;;;;   b(x) -> d(d(x))
;;;;   c(a(x)) -> a(x)
;;;;   c(c(x)) -> d(d(d(x)))
;;;;   c(d(x)) -> a(x)
;;;;   d(a(x)) -> a(x)
;;;;   d(d(d(c(x)))) -> a(x)
;;;;   d(d(d(d(x)))) -> a(x)
;;;;   e(a(x)) -> a(e(x))
;;;;   e(c(x)) -> a(e(x))
;;;;   e(d(x)) -> a(e(x))
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("A" "D" "C" "E" "B")
 :rules
 ((("A" ("A" (:VAR 0))) ("A" (:VAR 0)))
  (("A" ("C" (:VAR 0))) ("A" (:VAR 0)))
  (("A" ("D" (:VAR 0))) ("A" (:VAR 0)))
  (("B" (:VAR 0)) ("D" ("D" (:VAR 0))))
  (("C" ("A" (:VAR 0))) ("A" (:VAR 0)))
  (("C" ("C" (:VAR 0))) ("D" ("D" ("D" (:VAR 0)))))
  (("C" ("D" (:VAR 0))) ("A" (:VAR 0)))
  (("D" ("A" (:VAR 0))) ("A" (:VAR 0)))
  (("D" ("D" ("D" ("C" (:VAR 0))))) ("A" (:VAR 0)))
  (("D" ("D" ("D" ("D" (:VAR 0))))) ("A" (:VAR 0)))
  (("E" ("A" (:VAR 0))) ("A" ("E" (:VAR 0))))
  (("E" ("C" (:VAR 0))) ("A" ("E" (:VAR 0))))
  (("E" ("D" (:VAR 0))) ("A" ("E" (:VAR 0))))))
