;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: TPTP_COL053-1_theory.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   response(compose(x,y),z) -> response(x,response(y,z))
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("COMPOSE" "RESPONSE")
 :rules
 ((("RESPONSE" ("COMPOSE" (:VAR 0) (:VAR 1)) (:VAR 2)) ("RESPONSE" (:VAR 0) ("RESPONSE" (:VAR 1) (:VAR 2))))))
