;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: TPTP_SWV262-2_theory.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   c_union(C_EMPTYSET,y,x) -> y
;;;;   c_union(c_insert(x,y,w),z,w) -> c_insert(x,c_union(y,z,w),w)
;;;;   c_union(c_message_oparts(x),c_message_oparts(y),TC_MESSAGE_OMSG) -> c_message_oparts(c_union(x,y,TC_MESSAGE_OMSG))
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("C_EMPTYSET" "TC_MESSAGE_OMSG" "C_MESSAGE_OPARTS" "C_INSERT" "C_UNION")
 :rules
 ((("C_UNION" "C_EMPTYSET" (:VAR 0) (:VAR 1)) (:VAR 0))
  (("C_UNION" ("C_INSERT" (:VAR 0) (:VAR 1) (:VAR 2)) (:VAR 3) (:VAR 2)) ("C_INSERT" (:VAR 0) ("C_UNION" (:VAR 1) (:VAR 3) (:VAR 2)) (:VAR 2)))
  (("C_UNION" ("C_MESSAGE_OPARTS" (:VAR 0)) ("C_MESSAGE_OPARTS" (:VAR 1)) "TC_MESSAGE_OMSG") ("C_MESSAGE_OPARTS" ("C_UNION" (:VAR 0) (:VAR 1) "TC_MESSAGE_OMSG")))))
