;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: TPTP_GRP393-2_theory.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   multiply(multiply(x,y),z) -> multiply(x,multiply(y,z))
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("MULTIPLY")
 :rules
 ((("MULTIPLY" ("MULTIPLY" (:VAR 0) (:VAR 1)) (:VAR 2)) ("MULTIPLY" (:VAR 0) ("MULTIPLY" (:VAR 1) (:VAR 2))))))
