;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: TPTP_HWC004-2_theory.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   and(x,N0) -> N0
;;;;   and(x,N1) -> x
;;;;   not(N0) -> N1
;;;;   not(N1) -> N0
;;;;   or(x,N0) -> x
;;;;   or(x,N1) -> N1
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("N0" "N1" "NOT" "AND" "OR")
 :rules
 ((("AND" (:VAR 0) "N0") "N0")
  (("AND" (:VAR 0) "N1") (:VAR 0))
  (("NOT" "N0") "N1")
  (("NOT" "N1") "N0")
  (("OR" (:VAR 0) "N0") (:VAR 0))
  (("OR" (:VAR 0) "N1") "N1")))
