;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: TPTP_GRP012-4_theory.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   inverse(IDENTITY) -> IDENTITY
;;;;   inverse(inverse(x)) -> x
;;;;   inverse(multiply(y,x)) -> multiply(inverse(x),inverse(y))
;;;;   multiply(IDENTITY,x) -> x
;;;;   multiply(x,IDENTITY) -> x
;;;;   multiply(x,inverse(x)) -> IDENTITY
;;;;   multiply(x,multiply(inverse(x),y)) -> y
;;;;   multiply(inverse(x),x) -> IDENTITY
;;;;   multiply(inverse(x),multiply(x,y)) -> y
;;;;   multiply(multiply(x,y),z) -> multiply(x,multiply(y,z))
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("IDENTITY" "MULTIPLY" "INVERSE")
 :rules
 ((("INVERSE" "IDENTITY") "IDENTITY")
  (("INVERSE" ("INVERSE" (:VAR 0))) (:VAR 0))
  (("INVERSE" ("MULTIPLY" (:VAR 0) (:VAR 1))) ("MULTIPLY" ("INVERSE" (:VAR 1)) ("INVERSE" (:VAR 0))))
  (("MULTIPLY" "IDENTITY" (:VAR 0)) (:VAR 0))
  (("MULTIPLY" (:VAR 0) "IDENTITY") (:VAR 0))
  (("MULTIPLY" (:VAR 0) ("INVERSE" (:VAR 0))) "IDENTITY")
  (("MULTIPLY" (:VAR 0) ("MULTIPLY" ("INVERSE" (:VAR 0)) (:VAR 1))) (:VAR 1))
  (("MULTIPLY" ("INVERSE" (:VAR 0)) (:VAR 0)) "IDENTITY")
  (("MULTIPLY" ("INVERSE" (:VAR 0)) ("MULTIPLY" (:VAR 0) (:VAR 1))) (:VAR 1))
  (("MULTIPLY" ("MULTIPLY" (:VAR 0) (:VAR 1)) (:VAR 2)) ("MULTIPLY" (:VAR 0) ("MULTIPLY" (:VAR 1) (:VAR 2))))))
