;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: TPTP_HWC004-1_theory.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   and(N0,N0) -> N0
;;;;   and(N0,N1) -> N0
;;;;   and(N1,N0) -> N0
;;;;   and(N1,N1) -> N1
;;;;   not(N0) -> N1
;;;;   not(N1) -> N0
;;;;   or(N0,N0) -> N0
;;;;   or(N0,N1) -> N1
;;;;   or(N1,N0) -> N1
;;;;   or(N1,N1) -> N1
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("N0" "N1" "AND" "NOT" "OR")
 :rules
 ((("AND" "N0" "N0") "N0")
  (("AND" "N0" "N1") "N0")
  (("AND" "N1" "N0") "N0")
  (("AND" "N1" "N1") "N1")
  (("NOT" "N0") "N1")
  (("NOT" "N1") "N0")
  (("OR" "N0" "N0") "N0")
  (("OR" "N0" "N1") "N1")
  (("OR" "N1" "N0") "N1")
  (("OR" "N1" "N1") "N1")))
