;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: TPTP_COL085-1_theory.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   response(A,B) -> B
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("A" "B" "RESPONSE")
 :rules
 ((("RESPONSE" "A" "B") "B")))
