;;;; AUTO-GENERATED by tests/tools/generate-completion-expected.lisp
;;;; 手動編集しないこと。再生成はスクリプト冒頭の使い方を参照。
;;;; source: TPTP_BOO027-1_theory.trs
;;;;
;;;; 参考: 規則の可読表示（canonical-rewrite-rule-key 順）
;;;;   add(x,inverse(x)) -> ONE
;;;;   add(multiply(y,x),multiply(z,x)) -> multiply(x,add(y,z))
;;;;   add(multiply(x,inverse(x)),multiply(y,ONE)) -> y
;;;;   add(multiply(y,inverse(x)),multiply(y,add(y,inverse(x)))) -> y
;;;;   add(multiply(y,inverse(x)),multiply(x,add(y,inverse(x)))) -> y
(:term-order-algorithm :LPO
 :giveup-threshold 15
 :ordering ("ONE" "MULTIPLY" "INVERSE" "ADD")
 :rules
 ((("ADD" (:VAR 0) ("INVERSE" (:VAR 0))) "ONE")
  (("ADD" ("MULTIPLY" (:VAR 0) (:VAR 1)) ("MULTIPLY" (:VAR 2) (:VAR 1))) ("MULTIPLY" (:VAR 1) ("ADD" (:VAR 0) (:VAR 2))))
  (("ADD" ("MULTIPLY" (:VAR 0) ("INVERSE" (:VAR 0))) ("MULTIPLY" (:VAR 1) "ONE")) (:VAR 1))
  (("ADD" ("MULTIPLY" (:VAR 0) ("INVERSE" (:VAR 1))) ("MULTIPLY" (:VAR 0) ("ADD" (:VAR 0) ("INVERSE" (:VAR 1))))) (:VAR 0))
  (("ADD" ("MULTIPLY" (:VAR 0) ("INVERSE" (:VAR 1))) ("MULTIPLY" (:VAR 1) ("ADD" (:VAR 0) ("INVERSE" (:VAR 1))))) (:VAR 0))))
