name: release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  releaseapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Roswell
        env:
          LISP: sbcl-bin
        run: |
          curl -L https://raw.githubusercontent.com/roswell/roswell/master/scripts/install-for-ci.sh | sh
      - name: Install libraries that cannot be installed with quicklisp
        run: |
          ros install massung/lexer
      - name: Create Build
        run: |
          ros dump --delete-debug-info --remove-docstrings --purify --disable-compression executable ./roswell/clover-build.ros
      - name: Create release and upload asset
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          asset="clover-linux-x86_64_${GITHUB_REF_NAME}"
          mv ./roswell/clover-build "${asset}"
          gh release create "${GITHUB_REF_NAME}" "${asset}" \
            --repo "${GITHUB_REPOSITORY}" \
            --title "${GITHUB_REF_NAME}" \
            --notes ""
